name: randomkit
description: A new Flutter plugin.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter



  # IO
  # https://pub.dev/packages/dio
  dio: ^4.0.0
  # https://pub.dev/packages/dio_flutter_transformer
  dio_flutter_transformer: 
    git: https://github.com/randomjoho/dio_flutter_transformer.git

  # UI
  # https://pub.dev/packages/bot_toast
  bot_toast: ^4.0.1
  # https://pub.dev/packages/extended_image
  extended_image: ^4.1.0
  # https://pub.dev/packages/flutter_staggered_grid_view
  flutter_staggered_grid_view: ^0.4.0
  # https://pub.dev/packages/scrollable_positioned_list
  scrollable_positioned_list: ^0.1.10


  # Foundation
  # https://pub.dev/packages/decimal
  decimal: ^1.2.0
  # https://pub.flutter-io.cn/packages/intl
  intl: ^0.17.0
  # https://pub.dev/packages/json_serializable
  json_serializable: ^4.1.3
  # https://pub.dev/packages/logger
  logger: ^1.0.0-nullsafety.0
  # https://pub.dev/packages/package_info
  package_info: ^2.0.2

  # https://pub.dev/packages/pull_to_refresh
  pull_to_refresh: ^2.0.0
  # https://pub.dev/packages/url_launcher
  url_launcher: ^5.7.10



dependency_overrides:
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Build Tool
  # https://pub.dev/packages/build_runner
  build_runner: ^2.0.5

  # Other
  # https://pub.dev/packages/permission_handler
  permission_handler: ^8.1.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.plugin.randomkit
        pluginClass: RandomkitPlugin
      ios:
        pluginClass: RandomkitPlugin

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages

  assets:

  # assets start

  # GENERATED CODE - DO NOT MODIFY MANUALLY
  # **************************************************************************
  # Auto generated by https://github.com/fluttercandies/assets_generator
  # **************************************************************************

    - assets/
    - assets/toast_icon_done.png
    - assets/toast_icon_error.png

  # assets end
