// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************
class RandomRes {
  const RandomRes._();
  static const String assets_dialog_failed_png = 'assets/dialog_failed.png';

  static const String assets_dialog_success_png = 'assets/dialog_success.png';
}
