// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************
class RandomRes {
  const RandomRes._();
  static const String assets_empty = 'assets/empty';

  static const String assets_toast_icon_done_png = 'assets/toast_icon_done.png';

  static const String assets_toast_icon_error_png =
      'assets/toast_icon_error.png';
}
